mypy: Autospec creation for update from version 0.910 to version 0.920
97littleleaf11 (34):
      [mypyc] Add 'range' primitive type (#10307)
      [mypyc] Raise ImportError instead of AttributeError when from-import fails (#10641)
      [mypyc] Only construct dict setdefault collection when needed (#10668)
      [mypyc] Delete outdated TODOs (#10698)
      [mypyc] Add tests for str format() and fstring (#10729)
      [mypyc] Add a special case for len() of a str value (#10710)
      [mypyc] Add a str.format specializer which only supports empty brackets (#10697)
      [mypyc] Rewrite CPyStr_Build using a simplification of _PyUnicode_JoinArray (#10762)
      [mypyc] Faster int conversion in str.format (#10774)
      [mypyc] Initial optimization for f-string through a str.join() specializer (#10776)
      Use docstring in specialize.py (#10836)
      [mypyc] Tokenizer for printf-style format string (#10808)
      [mypyc] Build lists using a primitive op (#10807)
      Fix %c string and bytes interpolation (#10869)
      Use customized error message for %c interpolation (#10875)
      [mypyc] Add bytes primitive type (#10881)
      [mypyc] Use mypy.FORMAT_RE and ConversionSpecifier for % interpolation (#10877)
      [mypyc] Add bytearray support (#10891)
      [mypyc] Refactor: reuse format string parser (#10894)
      [mypyc] Add bytes and bytearray initialization ops (#10900)
      [mypyc] Faster len(bytes) (#10936)
      [mypyc] Add tests for chr(), ord(), encode() and decode() (#10914)
      [mypyc] Add bytes concat op (#10926)
      [mypyc] Introduce FormatOp and add a tokenizer for .format() call (#10935)
      [mypyc] Speed up string formatting using FormatOp (#10942)
      [mypyc] Add bytes index primitive (#10950)
      [mypyc] Add primitive for bytes.decode (#10951)
      Add primitives for str.encode() (#10974)
      [mypyc] Add primitive for bytes slicing (#10966)
      [mypyc] Faster bytes formatting (#10989)
      Fix typo and indent (#10995)
      Use context manager for Scope (#11053)
      Use property instead of method (#11068)
      Migrate tests from Travis.ci to Github Action (#11073)

Abdul Rehaman (1):
      Changed DIGIT.DIGIT to MAJOR.MINOR (#11281)

Adrian Freund (1):
      Consider variance when joining generic types (#9994)

Anders Kaseorg (1):
      Document ‘strict’ config file option (#11132)

Anmol Takiar (2):
      refactor: add contextmanager to VariableRenameVisitor (#10685)
      Better message if method incompatible with base class (#10572)

Anton Agestam (1):
      Document use of `...` in overloads (#10772)

Chad Dombrova (1):
      [stubgen] Fix a few bugs with stubgen of c modules (#11096)

Christoph Tyralla (2):
      Fix ad hoc instance intersection logic (#9909)
      Report attribute access errors for TypeVar bound to Union (#11140)

Daniel Hahler (1):
      Fix minor grammar issue in docs (#11106)

Dong-hee Na (1):
      bpo-45122: Remove PyCode_New from mypyc (#11067)

Elisha Hollander (1):
      Remove redundant `import`'s and `type_obj` (#10839)

Ethan Smith (3):
      Fix mypy for new virtualenv (#10855)
      Try removing skipped test on macOS (#10934)
      Fix PEP 561 tests for latest pip (#11356)

Henry Schreiner (1):
      docs: updating URL in comment (#10693)

Hugues (1):
      typeops: extend make_simplified_union fast path to enums (#9394)

Ilya Konstantinov (9):
      Improve pytest quality of life (#10567)
      Unreachable expressions: treat non-zero ints as truthy (#10562)
      Convert MessageBuilder.disable_errors to a context manager (#10569)
      check_boolean_op: clean up semanal/type-based reachability (#10566)
      Fix testNonBooleanContainsReturnValue (#10677)
      fix testSemanticAnalysisFalseButTypeNarrowingTrue (#10676)
      Check __bool__s in MRO for Literal return type (#10678)
      Check expr that are implicitly true for lack dunder bool/len (#10666)
      error_code_list2.rst: typo + edit (#11052)

Ivan Levkivskyi (9):
      A sketchy hack to fix TypeGuard crash in logical expressions (#11015)
      Fix crash on join of recursive types (#11433)
      Clear type alias flag for assignments that are not aliases (#11446)
      Fix bad cherry-pick
      Try fixing union inference including Any (#11460)
      Use implementation artifact Any for constraint target (#11523)
      Allow keyword arguments in __setattr__ (#11525)
      Fix cherry-pick
      Bump version

James (1):
      [mypyc] Fix relative imports in `__init__.py`s (#10543)

Jelle Zijlstra (1):
      Don't suggest installing types-pycrypto (#10603)

Jukka Lehtosalo (34):
      Include typeshed LICENSE (#10578)
      Restrict the number of errors shown when there are missing stubs (#10579)
      Make ignore_missing_imports work for libs which had bundled stubs (#10582)
      [mypyc] Only allow deleting attributes declared using __deletable__ (#10524)
      [mypyc] Fix evaluation of iterable in list comprehension twice (#10599)
      Bump version to 0.910+dev (#10607)
      Fix confusion between stubs for google.protobuf and google.cloud (#10609)
      Don't suggest incompatible stub packages (#10610)
      Support --install-types --non-interactive that doesn't prompt (#10616)
      Improve error reporting when --install-types has no cache (#10667)
      Run build a second time when using --install-types --non-interactive  (#10669)
      Document --install-types --non-interactive (#10684)
      Fix crash with assignment to variable guarded with TypeGuard (#10683)
      Don't ask to install a stub package if stubs are installed (#10670)
      [mypyc] Support various number-related dunders (#10679)
      Fix crash when inferring multiple assignment with overloaded function (#10689)
      Replace variable annotation with type comment to fix Python 3.5 (#10690)
      Bump version to 0.920+dev (#10702)
      [mypyc] Fix class-based named tuples (#10746)
      Fixes to generic builtin types (#10766)
      Support union type syntax in runtime contexts (#10770)
      Support new union syntax in stubs always in runtime context  (#10771)
      Support new union type syntax with isinstance (#10775)
      [mypyc] Reject instance attribute access through class object (#10798)
      [mypyc] Refactor: rename c_unary_op to unary_op (#10803)
      Improve type inference special case that involves union with Any (#10887)
      Fix self check (#10927)
      [mypyc] Fix division of negative tagged int (#11168)
      Fix crash related to AST diff of ParamSpec in mypy daemon (#11567)
      Revert "Fix callable instance variable support (#10548)" (#11571)
      logging: Make LoggerAdapter and StreamHandler generic in Python 2
      Add getattr overload variants to help mypy type inference
      Don't crash on unsupported Python 3.10 match statement (#11738)
      Fix crash when encountering match statement (#11749)

Kevin Wojniak (1):
      Fix typos in running_mypy.rst (#10794)

Konstantin Weddige (1):
      Remove misleading list of default locations (#10614)

KotlinIsland (1):
      Upgrade tomli (#11729)

Louis Sautier (1):
      Fix testAsync, test_stdlibsamples and testSrcPEP420Packages with Python 3.10 (#11017)

Max Marrone (1):
      Document how `--no-implicit-reexport` handles `from X import Y as Z` (#11083)

Mehdi ABAAKOUK (1):
      Ignore associated notes with ignore[typeddict-item] (#10975)

Michael J. Sullivan (16):
      [mypyc] Produce unimplemented errors on unsupported async features (#10595)
      Try ignoring Anys in type object callables for purposes of overload ambiguity (#10734)
      Make --cache-fine-grained imply --local-partial-types (#10737)
      Make ARG_* into an actual enum class instead of just using int everywhere (#10789)
      Use helper methods for a lot of ArgKind checks (#10793)
      Make refcounting handle error values loaded into registers (#10819)
      Properly track positional-only arguments for unannotated functions (#10802)
      Fix handling of default arguments in generated glue methods (#10825)
      [mypyc] Fix fastcall positional fast path when parser is uninitialized (#10834)
      Make the test system marginally less hostile to external reuse (#10919)
      Make the handling of ControlOp targets more generic (#10920)
      Add an xfailed test for issue #9852 (#10932)
      Pin tomli to 1.1.0 (#10938)
      Fix caching behavior of PEP561-installed namespace packages (#10937)
      Switch to using Id functions everywhere in lib-rt and dropping format calls (#10941)
      Support making a variable Optional in an else branch (#11002)

Michael R. Crusoe (1):
      Detect conda gcc for -Wno-unused-but-set-variable as well (#11112)

Momoko Hattori (1):
      Fix argument checking on empty dict with double stars (#9629)

Nikita Sobolev (20):
      Updates docs in 'checkexpr.py' and fixes a TODO (#10630)
      Fixes several typos in semanal.py (#10792)
      Fixes typos in mypyc (#10800)
      Improves `urls` on https://pypi.org/project/mypy (#10859)
      Adds docs about exhaustive literal and enum checks (#10860)
      Adds docs for TypeGuard type (#10758)
      Removes unused import (#11041)
      Removes unused `mypy.errors` import from `stubgen` (#11042)
      Update type narrowing section in`common_issues.rst` (#11014)
      Fixes `raise CustomError` creationg with  `__init__` with arguments (#11125)
      Fixes TypedDict crash with function definition (#11126)
      Fixes `misc/proper_plugin` crash on `isinstance(1)` (#11136)
      Fixes crash on partial `None` (#11134)
      Adds better type narrowing docs (#11088)
      Adds support for `__slots__` assignment (#10864)
      Fix mypy crash on `dataclasses.field(**unpack)` (#11137)
      Adds docs about `:=` and `TypeGuard` (#11161)
      Add type narrowing docs about `callable` (#11174)
      Docs for new `__slots__` feature (#11186)
      Properly check `*CustomType` and `**CustomType` arguments (#11151)

Niklas Gustafsson (1):
      Add OR regex example to --exclude docs (#10903)

Nipunn Koorapati (1):
      Remove unused variable in testpep561.py (#11114)

Peilonrayz (1):
      Fix recursion issue with nested instances and unions (#9663)

Richard Si (1):
      Optimize construction via list() & dict() (#10918)

Sebastian Rittau (9):
      stubgen: Use PEP 604 instead of Optional (#10624)
      stubgen: Use NamedTuple class syntax (#10625)
      stubgen: never generate variable initializer (#10623)
      stubgen: Don't annotate unknown argument and return types (#10626)
      Don't suggest to install stubs with py.typed files (#10652)
      pyopenssl types package name was corrected (#10656)
      pkg_resources is now in types-setuptools (#10681)
      stubgen: Add support for yield statements (#10745)
      Bump typed_ast max dependency (#11560)

Shantanu (31):
      Sync typeshed (#10537)
      Fix faulty casts in checker (#10560)
      Drop Python 3.5 support (#10706)
      Use variable annotations (#10723)
      Fix ParamSpec semanal issue (#10866)
      stubtest: import submodules mentioned in __all__ (#9943)
      stubtest: be safer with inspect.signature (#10884)
      Document per-module follow_imports more explicitly (#10845)
      stubtest: check type aliases (#10908)
      Skip overlapping overload checks in ignored files (#10922)
      Turn on ParamSpec semanal by default (#10883)
      Merge TypeVarDef and TypeVarType (#9951)
      Fix deserialisation of ParamSpecType (#10923)
      Add __path__ to package __init__ (#9454)
      Sync typeshed (#10862)
      Sync typeshed (#10924)
      Fix test failures caused by merge race (#10925)
      Sync typeshed (#11035)
      Recognise typeshed submodules in VERSIONS (#11069)
      Fix type guard crashes (#11061)
      Use descriptive names in CI (#11104)
      Don't trigger wheel builds on forks (#11124)
      Sync typeshed (#11123)
      Run tests on release branches (#11409)
      [mypyc] fix build on windows (#11316)
      Fix build_wheel script nits (#11312)
      Make error more self-explanatory when missing stubs or py.typed (#11262)
      Fix ReadTheDocs build on release branch (#11570)
      Fix crash with overload and callable object decorators (#11630)
      Fix crash involving explicit reexport, import cycle, wildcard (#11632)
      Add Python 3.10 to trove classifiers (#11747)

Smart (1):
      Update docs for deferral of PEP 563 to 3.11 (#10655)

Sorin Sbarnea (1):
      Document typing information inside sdist (#9684)

Taneli Hukkinen (2):
      Switch from `toml` to `tomli` for TOML v1 support (#10824)
      Disable universal newlines when reading TOML (#10893)

Terence Honles (1):
      update --warn-unreachable to respect if the code should be type checked (#10291)

Tim Gallant (1):
      [dataclasses plugin] Support kw_only=True (#10867)

Timofey Kukushkin (1):
      Add __dataclass_fields__ and __attrs_attrs__ to dataclasses (#8578)

Vanessa Ung (1):
      stubgen: Handle commas in namedtuple field definition (#10828)

Zac Hatfield-Dodds (1):
      Allow slice syntax (#11406)

ethframe (1):
      Narrow type with typevar when the upper bound is a subtype (#10658)

geo7 (1):
      Update getting_started.rst (#10720)

hatal175 (1):
      Plugin for tuple multiplication with literal int (#10361)

jhance (3):
      Add primitive for bytes join() method (#10929)
      [mypyc] Implement bytes equality optimizations (#10928)
      [mypyc] Remove decorator_helper_name (#11022)

pranavrajpal (26):
      [mypyc] Fix segfault when top level raises exception (#10586)
      [mypyc] Avoid crash when importing unknown module with from import (#10550)
      Add support for using xfail in test cases (#10635)
      [mypyc] Add cleanup at end of init function (#10590)
      [mypyc] Add mypyc run tests for singledispatch (#10589)
      Add tests for singledispatch (#10627)
      Call get_method_hook when methods are used in decorators (#10675)
      stubtest: add assert is not None for singledispatch plugin (#10716)
      Allow plugin signature hooks to return FunctionLike (#10717)
      Make verify first type a supertype of all dispatch types (#10727)
      Add initial singledispatch typechecking support (#10694)
      Preserve types of functions registered with singledispatch (#10756)
      [mypyc] Add initial support for compiling singledispatch functions (#10753)
      Avoid mutating the AST when processing register calls (#10779)
      [mypyc] Improve support for compiling singledispatch (#10795)
      Allow redefinition of underscore functions (#10811)
      Avoid crash in singledispatch plugin for incorrect singledispatch arguments (#10831)
      [mypyc] Add support for underscore functions (#10830)
      Pin virtualenv to 16.7.10 (#10853)
      [mypyc] Fix order of dispatch type checking in singledispatch functions (#10844)
      [mypyc] Allow registering implementations for singledispatch functions in different files (#10880)
      [mypyc] Use native calls in singledispatch dispatch functions (#10888)
      [mypyc] Use MRO of argument for dispatch in singledispatch functions (#10930)
      [mypyc] Add support for dynamically registering singledispatch functions (#10968)
      [mypyc] Use a cache to speed up singledispatch calls (#10972)
      [mypyc] Use native calls to singledispatch functions (#10981)

ryan-gunderson (1):
      Correct example annotation `self` (#11133)

sed-i (1):
      fix doc typo (#10992)

wyfo (1):
      Fix callable instance variable support (#10548)